Completed Assignment2
Rarkness/python pull request #2
Opened 2024-12-09 03:33 UTC by Rarkness

## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports) Completed assignment 2 questions with my code

## What did you learn from the changes you have made?
to make sure the path to the file is correct
## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of? Not really I'm pretty new at this :)

## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
I  was not able to create a PR as I didn't create a new branch
## How were these changes tested?
line by line
## A reference to a related issue in your repository (if applicable)

## Checklist
- [x ] I can confirm that my changes are working as intended

2024-12-10 04:29 UTC, anjali-deshpande-hub commented on 02_activities/assignments/assignment_1.ipynb
assignment_1.ipynb file changes should not be part of assignment-2. You probably created assignment-2 branch from assignment-1. Please correct this.

2024-12-10 04:34 UTC, anjali-deshpande-hub commented on 02_activities/assignments/assignment_2.ipynb
> +      "['0,0,1,3,1,2,4,7,8,3,3,3,10,5,7,4,7,7,12,18,6,13,11,11,7,7,4,6,8,8,4,4,5,7,3,4,2,3,0,0\\n', '0,1,2,1,2,1,3,2,2,6,10,11,5,9,4,4,7,16,8,6,18,4,12,5,12,7,11,5,11,3,3,5,4,4,5,5,1,1,0,1\\n', '0,1,
There is incorrect printing inside the loop. You are printing the entire contents list in each iteration of the loop (print(contents)), which is not the intended behaviour.  Instead, you should print each individual line (content).

2024-12-10 04:36 UTC, anjali-deshpande-hub commented on 02_activities/assignments/assignment_2.ipynb
> +      "['0,0,1,3,1,2,4,7,8,3,3,3,10,5,7,4,7,7,12,18,6,13,11,11,7,7,4,6,8,8,4,4,5,7,3,4,2,3,0,0\\n', '0,1,2,1,2,1,3,2,2,6,10,11,5,9,4,4,7,16,8,6,18,4,12,5,12,7,11,5,11,3,3,5,4,4,5,5,1,1,0,1\\n', '0,1,
Incorrect printing inside the loop. For every line in the file, you are printing first 5 lines of the file. This is not required.

2024-12-10 04:37 UTC, anjali-deshpande-hub requested changes
Please make the above mentioned changes and resubmit

2024-12-10 04:37 UTC, Rarkness commented
no idea how to do that

On Mon, Dec 9, 2024 at 8:30 PM anjali-deshpande-hub <
***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> On 02_activities/assignments/assignment_1.ipynb
> <https://github.com/Rarkness/python/pull/2#discussion_r1877285574>:
>
> assignment_1.ipynb file changes should not be part of assignment-2. You
> probably created assignment-2 branch from assignment-1. Please correct this.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Rarkness/python/pull/2#pullrequestreview-2490936099>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BM2HO56DQI6C3RPFJT3XYP32EZU45AVCNFSM6AAAAABTH5E4ZGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIOJQHEZTMMBZHE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-12-10 04:38 UTC, Rarkness commented
no idea what you mean or how to do this

On Mon, Dec 9, 2024 at 8:37 PM anjali-deshpande-hub <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Please make the above mentioned changes and resubmit
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Rarkness/python/pull/2#pullrequestreview-2490949895>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BM2HO54YDE4REBSW6R3YEE32EZVYBAVCNFSM6AAAAABTH5E4ZGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIOJQHE2DSOBZGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-12-10 18:57 UTC, closed without merging

2024-12-11 03:46 UTC, anjali-deshpande-hub commented on 02_activities/assignments/assignment_1.ipynb
Refer to https://uoft-dsi-certificates.slack.com/archives/C080M1JFJ8G/p1733888574840979 to correct this problem

2024-12-11 03:47 UTC, anjali-deshpande-hub commented
Please do not close your pull request until the review is complete and it has been approved by learning support. If further changes are requested, simply commit the updates to the same branch; the PR will automatically reflect the changes. There is no need to create a new PR.

2024-12-11 03:54 UTC, Rarkness commented
I don't need to run those commands. I closed the original pull and
resubmitted it with the correct changes as a new pull (I know don't do that
simply committing is all we have to do).
I had asked the question before doing that but didn't get an answer so I
did what I could.

On Tue, Dec 10, 2024 at 10:47 PM anjali-deshpande-hub <
***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> On 02_activities/assignments/assignment_1.ipynb
> <https://github.com/Rarkness/python/pull/2#discussion_r1879289629>:
>
> Refer to
> https://uoft-dsi-certificates.slack.com/archives/C080M1JFJ8G/p1733888574840979
> to correct this problem
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Rarkness/python/pull/2#discussion_r1879289629>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BM2HO55NBLLSICHNBUNYAJT2E6YTTAVCNFSM6AAAAABTH5E4ZGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIOJUGIZTKMZXGI>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>